#!/usr/bin/env python3
"""PreToolUse: block hand-edits to frontend/api/generated/.

That directory is regenerated by `pnpm -C frontend generate-client`; manual
edits get clobbered. Enforces the AGENTS.md rule for Claude Code. Exit 2
blocks the tool call and feeds stderr back to the agent.
"""

import json
import os
import sys

GUARDED = "/frontend/api/generated/"


def main() -> int:
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return 0  # unparseable input -> never block

    tool_input = data.get("tool_input") or {}
    # Accept any known path-bearing key so a schema/matcher change does not
    # silently disable the guard. If none is present, fail CLOSED: a security
    # guard must not allow an edit it could not inspect.
    file_path = tool_input.get("file_path") or tool_input.get("notebook_path")
    if not file_path:
        print(
            "Blocked: could not determine the target file path from the tool "
            "payload, so the frontend/api/generated/ guard cannot verify this "
            "edit is safe. Refusing by default. (See AGENTS.md.)",
            file=sys.stderr,
        )
        return 2

    project_dir = data.get("cwd") or os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    norm = os.path.abspath(os.path.join(project_dir, file_path)).replace(os.sep, "/")

    if GUARDED in norm:
        print(
            f"Blocked: {file_path} is under frontend/api/generated/, which is "
            "generated from the backend OpenAPI schema. Change the backend "
            "endpoint instead, then run `pnpm -C frontend generate-client`. "
            "(See AGENTS.md.)",
            file=sys.stderr,
        )
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
