"""add pair verdicts and pair rules tables

Revision ID: 2ffdfff5bb86
Revises: d3abe583f2da
Create Date: 2026-03-25 16:21:25.412088

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ffdfff5bb86"
down_revision: Union[str, None] = "d3abe583f2da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pair_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("type_pair", sa.String(length=100), nullable=False),
        sa.Column("feature_name", sa.String(length=100), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_pair_rules_active", "pair_rules", ["is_active"], unique=False)
    op.create_table(
        "pair_verdicts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("thread_id", sa.String(length=255), nullable=False),
        sa.Column("sample_a_id", sa.String(length=255), nullable=False),
        sa.Column("sample_b_id", sa.String(length=255), nullable=False),
        sa.Column("verdict", sa.Boolean(), nullable=False),
        sa.Column("pair_score", sa.Float(), nullable=False),
        sa.Column("pair_score_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("pair_features", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["sample_a_id"],
            ["samples.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sample_b_id"],
            ["samples.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_pair_verdicts_pair", "pair_verdicts", ["sample_a_id", "sample_b_id"], unique=False)
    op.create_index("ix_pair_verdicts_thread", "pair_verdicts", ["thread_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pair_verdicts_thread", table_name="pair_verdicts")
    op.drop_index("ix_pair_verdicts_pair", table_name="pair_verdicts")
    op.drop_table("pair_verdicts")
    op.drop_index("ix_pair_rules_active", table_name="pair_rules")
    op.drop_table("pair_rules")
    # ### end Alembic commands ###
