"""change bpm column from float to integer

Revision ID: 7d94cdcd4649
Revises: c1e3a6c19709
Create Date: 2026-03-23 20:42:37.027123

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d94cdcd4649"
down_revision: Union[str, None] = "c1e3a6c19709"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "samples", "bpm", existing_type=sa.DOUBLE_PRECISION(precision=53), type_=sa.Integer(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "samples", "bpm", existing_type=sa.Integer(), type_=sa.DOUBLE_PRECISION(precision=53), existing_nullable=True
    )
    # ### end Alembic commands ###
