"""add relative_path source pack_name to samples

Revision ID: 82874d1dc3a2
Revises: 7d94cdcd4649
Create Date: 2026-03-23 21:14:22.404248

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82874d1dc3a2"
down_revision: Union[str, None] = "7d94cdcd4649"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add relative_path as nullable first
    op.add_column("samples", sa.Column("relative_path", sa.String(length=512), nullable=True))
    op.add_column(
        "samples", sa.Column("source", sa.String(length=20), server_default=sa.text("'local'"), nullable=False)
    )
    op.add_column("samples", sa.Column("pack_name", sa.String(length=255), nullable=True))

    # Backfill relative_path from existing sample_type/filename
    op.execute(
        sa.text(
            "UPDATE samples SET relative_path = "
            "CASE WHEN sample_type IS NOT NULL THEN sample_type || '/' || filename "
            "ELSE filename END"
        )
    )

    # Make relative_path NOT NULL after backfill
    op.alter_column("samples", "relative_path", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("samples", "pack_name")
    op.drop_column("samples", "source")
    op.drop_column("samples", "relative_path")
    # ### end Alembic commands ###
