"""add_is_loop_column

Revision ID: c1e3a6c19709
Revises: f2483c5c35f2
Create Date: 2026-03-20 18:10:05.440003

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1e3a6c19709"
down_revision: Union[str, None] = "f2483c5c35f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("samples", sa.Column("is_loop", sa.Boolean(), nullable=False, server_default=sa.text("false")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("samples", "is_loop")
    # ### end Alembic commands ###
