"""add_song_context_to_threads

Revision ID: d3abe583f2da
Revises: e31d10150c8c
Create Date: 2026-03-24 15:50:39.765022

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d3abe583f2da"
down_revision: Union[str, None] = "e31d10150c8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("threads", sa.Column("song_context", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threads", "song_context")
    # ### end Alembic commands ###
