"""initial samples table with pgvector

Revision ID: f2483c5c35f2
Revises:
Create Date: 2026-03-19 17:14:37.531466

"""

from typing import Sequence, Union

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2483c5c35f2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "samples",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=10), nullable=True),
        sa.Column("bpm", sa.Float(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("sample_type", sa.String(length=50), nullable=True),
        sa.Column("clap_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
        sa.Column("cnn_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_samples_id"), "samples", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_samples_id"), table_name="samples")
    op.drop_table("samples")
    # ### end Alembic commands ###
